name = "jade-gems"
compatibility_date = "2024-01-01"

# Cloudflare Pages 配置
[build]
command = "npx @cloudflare/next-on-pages@1"
cwd = "."

[build.environment]
NODE_VERSION = "18"

# R2 绑定（可选，如果需要直接在 Workers 中访问 R2）
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "jade-gems-uploads"

# 环境变量（实际值在 Cloudflare Dashboard 中配置）
[vars]
# 这里不要放敏感信息，仅作为变量名参考

